### ISSUE TITLE
Storage not reducing down

### ISSUE THREAD

**Issue by Flowbird-Ltd** [Flowbird-Ltd/Havio#1]
Hi Mauricio, 

I am not sure why the storage of main isn't reducing down after deleting a large number of records from the system using SQL commands. 

These SQL commands are: 
cr.execute("DELETE from x_email_sync WHERE create_date > '2021-07-05 00:00:00'")
And:
env.cr.execute("DELETE from ir_attachment WHERE id in (select id from ir_attachment where res_model = 'x_email_sync' limit 100000);")
(as a cron job) 

I tried the exact same thing in staging which was working and reduced the size to ~20GB when deleting all the x_email_sync records. However, main is still ~50GB of data with a lot fewer records... (Using the monitor to view this) Odoo support hasn't been much help either... 

Let me know if you know what is the issue and how to fix it. 

Thanks for the help!

**Comment by mapuerta** [comment]
@Flowbird-Ltd Run it from odoo.sh console

**Comment by Flowbird-Ltd** [comment]
@mapuerta, sorry, what do you need to be run from the odoo.sh console?

**Comment by mapuerta** [comment]
@Flowbird-Ltd permissions. 

Why 

```sql

DELETE from ir_attachment WHERE id in (select id from ir_attachment where res_model = 'x_email_sync' limit 100000);

and not 

DELETE from ir_attachment WHERE res_model = 'x_email_sync'; 
```

Only want deleted 100000 records ?

**Comment by Flowbird-Ltd** [comment]
@mapuerta, 

I was speaking to Alfredo, I thought the data was cached but it's not, the records have actually been deleted. 

Alfredo did a rebuild onto V2 and the size of the x_email_sync file is 20GB in main. However, the size of V2 is 4600 kb, how is it possible that a rebuild has 20GB less data in a table? 

Any idea what would be causing this or how to free up that storage?

**Comment by mapuerta** [comment]
@Flowbird-Ltd  I do not understand the rebuild weighs more than the main one?

**Comment by Flowbird-Ltd** [comment]
@mapuerta, that's correct, you should have access to the Odoo.sh project Havio and you can see that the rebuild (V2) is 17GB where as main is 47GB.

**Comment by Flowbird-Ltd** [comment]
Response from Odoo, 
"
Dear Customer,

We can try to run SQL command vacuum; and see if it does the job, but please note that the command will slow your database for a few seconds /minutes.

Best regards.
"

**Comment by Flowbird-Ltd** [comment]
@mapuerta, 

It looked like the Vacuum worked to reduce the size of the database tables, are these SQL queries ok to run as scheduled actions? 

env.cr.execute("DELETE from mail_followers WHERE id in (select id from mail_followers where res_model = 'x_email_sync' limit 1000000);")

Followers seem to run quite fast so I am comfortable running 1,000,000 at a time. 

env.cr.execute("DELETE from mail_message WHERE id in (select id from mail_message where model = 'x_email_sync' limit 100000);")

I only want to delete followers and messages of the document x_email_sync so that I don't want to delete anything to do with sales etc. 

Thanks,

**Comment by mapuerta** [comment]
@Flowbird-Ltd Affirmative I see them well.
